name: kms
channels:
  - conda-forge
  - rmg
  - nodefaults
dependencies:
  - python>=3.7
  - nomkl
  - cairo
  - cairocffi
  - xlrd
  - xlwt
  - habanero>=0.6,<0.7
  - rmg==3.0
  - django==3.0
  - django-filter
  - django-extensions
  - django-model-utils
  - django-crispy-forms
  - psycopg2
  - gunicorn
  - pip
  - pip:
    - titlecase
    - black
    - flake8
    - flake8-django
    - django-test-migrations
